### PR TITLE
GH-10 Change command permission structure

### LINKED ISSUE #10: Add an option to change permissions of all commands
What are the commands and permissions? Can't find anywhere about them

### PR DESCRIPTION
**Pull request by imDMK**
Fixes #10 
This PR changes command structures:
- Command permissions are no longer configurable - They are permanently set.

List of command permissions:
- **/spenttime**: command.spenttime
- **/spenttime {TARGET}**: command.spenttime.other
- **/spenttime top**: command.spenttime.top
- **/spenttime reset**: command.spenttime.reset
- **/spenttime reset-all**: command.spenttime.reset.all
The change is because if permissions were still configurable, it would not be possible to configure a separate permission for **/spenttime {TARGET}**.

### CODE REVIEW

**Comment by SpLeNd1d222** [comment]
Commands are good and they are more important than permissions, so if it is not possible to leave the possibility to change them, so be it. And now it means that every player group, including the default, will have access to these commands, right?

**Comment by imDMK** [comment]
> Commands are good and they are more important than permissions, so if it is not possible to leave the possibility to change them, so be it. And now it means that every player group, including the default, will have access to these commands, right?

No. This means that by default a player without permissions will not be able to execute the spenttime command. To execute the command, it must have the specified permissions that I wrote above.

**Comment by imDMK** [comment]
Only the permissions have been changed - they are no longer editable, but permanently assigned to the command.
Let me know what you think about them.

**Comment by SpLeNd1d222** [comment]
I have one more question, what's the permission for the _/spenttime target_ command, because here it says it's **command.spenttime.other** but for example in #17 i noticed that it says it's **command.spenttime.target**. So how is it?

**Comment by imDMK** [comment]
On the main page https://github.com/imDMK/SpentTime you have actual information.

**Pull request merged**
